name: build_and_deploy
on: workflow_dispatch

env:
  IMAGE_NAME: ${{ secrets.REGISTRY }}/urban-assistant-client

jobs:
  build:
    name: Build Docker image
    runs-on: 16_runner
    outputs:
      tag: ${{ steps.date.outputs.NOW }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy env file
        env:
          ENV_PATH: ${{ secrets.ENV_PATH }}
        run: cp $ENV_PATH/service.env ./service.env


      - name: Get build tag
        id: date
        run: echo "NOW=$(date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build -t ${IMAGE_NAME}:${{ steps.date.outputs.NOW }} .

  deploy:
    name: Deploy container
    runs-on: 16_runner
    needs: build
    env:
      TAG: ${{ needs.build.outputs.tag }}
    
    steps:
      - name: Stop old container
        run: docker rm -f urban-assistant-client || true

      - name: Run new container
        run: |
          docker run -d \
            --name urban-assistant-client \
            --publish 3000:3100 \
            --restart unless-stopped \
            ${IMAGE_NAME}:$TAG
